services:
  - type: web
    name: ora-app
    env: python
    region: oregon
    buildCommand: cd server && pip install -r ../requirements.txt && cd ../client && npm install && npm run build && cp -r build/* ../server/public/ && cd ../server && chmod +x update_runtime_config.sh && ./update_runtime_config.sh
    startCommand: cd server && python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ora-db
          property: connectionString

databases:
  - name: ora-db
    databaseName: ora
    user: ora 