"""Add response_speed to User model

Revision ID: 3210787685b5
Revises: bf0bbfc77396
Create Date: 2025-04-01 22:52:51.077519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3210787685b5'
down_revision = 'bf0bbfc77396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_speed', sa.String(length=20), nullable=True))
        batch_op.alter_column('aura_color',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('aura_color',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
        batch_op.drop_column('response_speed')

    # ### end Alembic commands ###
