"""Add aura fields to Location model

Revision ID: abc5cb58f1f8
Revises: 887151d772f6
Create Date: 2025-04-04 12:20:02.251692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc5cb58f1f8'
down_revision = '887151d772f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('price_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_ratings_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('aura_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('aura_color', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('aura_shape', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('aura_shape')
        batch_op.drop_column('aura_color')
        batch_op.drop_column('aura_name')
        batch_op.drop_column('area')
        batch_op.drop_column('user_ratings_total')
        batch_op.drop_column('price_level')
        batch_op.drop_column('website')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
